#version: '3'

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6380:6379"  # Redis'in varsayılan portu
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5673:5672"  # RabbitMQ için mesaj kuyruğu portu
      - "15673:15672"  # RabbitMQ yönetim paneli portu
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
  web:
    container_name: marswide_backend
    image: marswide_backend
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    restart: always
    env_file:
      - .env
  celery:
    build:
      context: .
    container_name: celery
    command: celery -A core worker -l INFO
    depends_on:
      - redis
    volumes:
      - .:/app
  db:
    image: postgres:16
    container_name: postgres_db
    volumes:
      #- ./pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"
    restart: always
    env_file:
      - .env
volumes:
  postgres_data:
  redis_data: