version: '3'

services:
  web:
    image: marswide_backend
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    restart: always
    env_file:
      - .env
  db:
    image: postgres:16
    container_name: postgres_db
    volumes:
      #- ./pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"
    restart: always
    env_file:
      - .env
volumes:
  postgres_data: