services:
  web:
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      DJANGO_SETTINGS_MODULE: core.settings
  nginx:
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./staticfiles:/staticfiles
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
    restart: always