services:
  web:
    #command: gunicorn core.wsgi:application --bind 0.0.0.0:8000 --timeout 600 --log-level debug
    #command: gunicorn --access-logfile - --workers 33 --limit-request-line 6000 --bind unix:/run/gunicorn.sock core.asgi:application -k uvicorn.workers.UvicornWorker
    command: gunicorn --access-logfile - --workers 5 --limit-request-line 6000 --bind 0.0.0.0:8000 core.asgi:application -k uvicorn.workers.UvicornWorker
    environment:
      DJANGO_SETTINGS_MODULE: core.settings

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./staticfiles:/staticfiles
      - ./nginx/certificates:/etc/ssl/certs
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
    restart: always
  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    volumes:
      - ./nginx/certificates:/etc/letsencrypt
    entrypoint: /bin/sh -c 'while :; do certbot renew --non-interactive --quiet; sleep 12h; done'
    deploy:
      restart_policy:
        condition: any